name: Build OpenWrt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git subversion libssl-dev gettext unzip file libelf-dev ecj fastjar java-propose-classpath python3

      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          cp ../config .config
          make defconfig
          make download -j8
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/targets/
